# Disable default rules (which makes it easier to debug Makefile problems)
.SUFFIXES:

# Logic for automatic dependency generation below has been borrowed from:
# http://make.mad-scientist.net/papers/advanced-auto-dependency-generation/

$(OBJDIR)/%.o : $(SRCDIR)/%.c $(DEPDIR)/%.d | $(DEPDIR)/ $(OBJDIR)/
	$(CC) -MT $@ -MMD -MP -MF $(DEPDIR)/$*.d $(CFLAGS) -c -o $@ $<

$(OBJDIR)/%.o : $(SRCDIR)/%.cc $(DEPDIR)/%.d | $(DEPDIR)/ $(OBJDIR)/
	$(CXX) -MT $@ -MMD -MP -MF $(DEPDIR)/$*.d  $(CXXFLAGS) -c -o $@ $<

$(OBJDIR)/client/%.o : $(SRCDIR)/client/%.cc $(DEPDIR)/client/%.d | $(DEPDIR)/client/ $(OBJDIR)/client/
$(OBJDIR)/client/%.o : $(SRCDIR)/client/%.cc $(DEPDIR)/client/%.d | $(DEPDIR)/client/ $(OBJDIR)/client/
	$(CXX) -MT $@ -MMD -MP -MF $(DEPDIR)/client/$*.d $(CXXFLAGS) -c -o $@ $<

deps/: ; mkdir -p $@
deps/client/: ; mkdir -p $@
objs/: ; mkdir -p $@
objs/client/: ; mkdir -p $@

DEPFILES := $(C_SRCS:$(SRCDIR)/%.c=$(DEPDIR)/%.d) $(CXX_SRCS:$(SRCDIR)/%.cc=$(DEPDIR)/%.d)

$(DEPFILES):

include $(wildcard $(DEPFILES))

# Rules to build tests follow.

efcodec_test: $(OBJDIR)/efcodec_test.o $(OBJDIR)/efcodec.o
	$(CXX) $(CXXFLAGS) $(LDFLAGS) -o $@ $^ $(LDLIBS)

perms_test: $(OBJDIR)/perms_test.o $(OBJDIR)/perms.o $(OBJDIR)/board.o
	$(CXX) $(CXXFLAGS) $(LDFLAGS) -o $@ $^ $(LDLIBS)

search_test: $(OBJDIR)/search_test.o $(OBJDIR)/search.o $(OBJDIR)/board.o $(OBJDIR)/perms.o
	$(CXX) $(CXXFLAGS) $(LDFLAGS) -o $@ $^ $(LDLIBS)

ternary_test: $(OBJDIR)/ternary_test.o
	$(CXX) $(CXXFLAGS) $(LDFLAGS) -o $@ $^ $(LDLIBS)

test: $(TESTS)
	./efcodec_test
	./perms_test
	./search_test
	./ternary_test

# Rules to build binaries follow.

backpropagate-losses: $(OBJDIR)/backpropagate-losses.o $(COMMON_OBJS)
	$(CXX) $(CXXFLAGS) $(LDFLAGS) -o $@ $^ $(LDLIBS)

backpropagate2: $(OBJDIR)/backpropagate2.o $(COMMON_OBJS) $(CLIENT_OBJS) $(SOLVER_OBJS)
	$(CXX) $(CXXFLAGS) $(LDFLAGS) -o $@ $^ $(LDLIBS) $(CLIENT_LDLIBS)

count-bits: $(OBJDIR)/count-bits.o
	$(CXX) $(CXXFLAGS) $(LDFLAGS) -o $@ $^ $(LDLIBS)

count-bytes: $(OBJDIR)/count-bytes.o
	$(CXX) $(CXXFLAGS) $(LDFLAGS) -o $@ $^ $(LDLIBS)

count-r1: $(OBJDIR)/count-r1.o
	$(CXX) $(CXXFLAGS) $(LDFLAGS) -o $@ $^ $(LDLIBS)

count-unreachable: $(OBJDIR)/count-unreachable.o $(COMMON_OBJS)
	$(CXX) $(CXXFLAGS) $(LDFLAGS) -o $@ $^ $(LDLIBS)

combine-bitmaps: $(OBJDIR)/combine-bitmaps.o
	$(CC) $(CCFLAGS) $(LDFLAGS) -o $@ $^ $(LDLIBS)

combine-two: $(OBJDIR)/combine-two.o $(COMMON_OBJS)
	$(CXX) $(CXXFLAGS) $(LDFLAGS) -o $@ $^ $(LDLIBS)

decode-delta: $(OBJDIR)/decode-delta.o $(COMMON_OBJS)
	$(CXX) $(CXXFLAGS) $(LDFLAGS) -o $@ $^ $(LDLIBS)

encode-delta: $(OBJDIR)/encode-delta.o $(COMMON_OBJS)
	$(CXX) $(CXXFLAGS) $(LDFLAGS) -o $@ $^ $(LDLIBS)

expand-minimized: $(OBJDIR)/expand-minimized.o $(COMMON_OBJS) $(LOOKUP_OBJS)
	$(CXX) $(CXXFLAGS) $(LDFLAGS) -o $@ $^ $(LDLIBS) $(LOOKUP_LDLIBS)

fix-r4-bin: $(OBJDIR)/fix-r4-bin.o $(COMMON_OBJS)
	$(CXX) $(CXXFLAGS) $(LDFLAGS) -o $@ $^ $(LDLIBS)

integrate-wins: $(OBJDIR)/integrate-wins.o $(COMMON_OBJS)
	$(CXX) $(CXXFLAGS) $(LDFLAGS) -o $@ $^ $(LDLIBS)

integrate-wins2: $(OBJDIR)/integrate-wins2.o $(COMMON_OBJS)
	$(CXX) $(CXXFLAGS) $(LDFLAGS) -o $@ $^ $(LDLIBS)

integrate-two: $(OBJDIR)/integrate-two.o $(COMMON_OBJS)
	$(CXX) $(CXXFLAGS) $(LDFLAGS) -o $@ $^ $(LDLIBS)

lookup-min: $(OBJDIR)/lookup-min.o $(COMMON_OBJS) $(LOOKUP_OBJS)
	$(CXX) $(CXXFLAGS) $(LDFLAGS) -o $@ $^ $(LDLIBS) $(LOOKUP_LDLIBS)

lookup-rN: $(OBJDIR)/lookup-rN.o $(COMMON_OBJS)
	$(CXX) $(CXXFLAGS) $(LDFLAGS) -o $@ $^ $(LDLIBS)

minify-merged: $(OBJDIR)/minify-merged.o $(COMMON_OBJS)
	$(CXX) $(CXXFLAGS) $(LDFLAGS) -o $@ $^ $(LDLIBS)

merge-phases: $(OBJDIR)/merge-phases.o $(COMMON_OBJS) $(OBJDIR)/lost-positions.o
	$(CXX) $(CXXFLAGS) $(LDFLAGS) -o $@ $^ $(LDLIBS)

minimax: $(OBJDIR)/minimax.o $(COMMON_OBJS)
	$(CXX) $(CXXFLAGS) $(LDFLAGS) -o $@ $^ $(LDLIBS)

print-ef: $(OBJDIR)/print-ef.o $(OBJDIR)/bytes.o $(OBJDIR)/efcodec.o $(OBJDIR)/parse-int.o
	$(CXX) $(CXXFLAGS) $(LDFLAGS) -o $@ $^ $(LDLIBS)

print-perm: $(OBJDIR)/print-perm.o $(COMMON_OBJS)
	$(CXX) $(CXXFLAGS) $(LDFLAGS) -o $@ $^ $(LDLIBS)

print-r1: $(OBJDIR)/print-r1.o
	$(CXX) $(CXXFLAGS) $(LDFLAGS) -o $@ $^ $(LDLIBS)

potential-new-losses: $(OBJDIR)/potential-new-losses.o $(COMMON_OBJS) $(SOLVER_OBJS)
	$(CXX) $(CXXFLAGS) $(LDFLAGS) -o $@ $^ $(LDLIBS) $(CLIENT_LDLIBS)

pushfight-standalone-server: $(OBJDIR)/pushfight-standalone-server.o $(COMMON_OBJS) $(LOOKUP_OBJS)
	$(CXX) $(CXXFLAGS) $(LDFLAGS) -o $@ $^ $(LDLIBS) $(LOOKUP_LDLIBS)

sample-bytes: $(OBJDIR)/sample-bytes.o
	$(CXX) $(CXXFLAGS) $(LDFLAGS) -o $@ $^ $(LDLIBS)

solve2: $(OBJDIR)/solve2.o $(COMMON_OBJS) $(CLIENT_OBJS) $(SOLVER_OBJS)
	$(CXX) $(CXXFLAGS) $(LDFLAGS) -o $@ $^ $(LDLIBS) $(CLIENT_LDLIBS)

solve3: $(OBJDIR)/solve3.o $(COMMON_OBJS) $(CLIENT_OBJS) $(SOLVER_OBJS)
	$(CXX) $(CXXFLAGS) $(LDFLAGS) -o $@ $^ $(LDLIBS) $(CLIENT_LDLIBS)

solve-r0: $(OBJDIR)/solve-r0.o $(COMMON_OBJS)
	$(CXX) $(CXXFLAGS) $(LDFLAGS) -o $@ $^ $(LDLIBS)

solve-r1: $(OBJDIR)/solve-r1.o $(COMMON_OBJS)
	$(CXX) $(CXXFLAGS) $(LDFLAGS) -o $@ $^ $(LDLIBS)

solve-rN: $(OBJDIR)/solve-rN.o $(COMMON_OBJS) $(CLIENT_OBJS) $(SOLVER_OBJS)
	$(CXX) $(CXXFLAGS) $(LDFLAGS) -o $@ $^ $(LDLIBS) $(CLIENT_LDLIBS)

solve-lost: $(OBJDIR)/solve-lost.o $(COMMON_OBJS)
	$(CXX) $(CXXFLAGS) $(LDFLAGS) -o $@ $^ $(LDLIBS)

verify-input-chunks: $(OBJDIR)/verify-input-chunks.o $(COMMON_OBJS) $(OBJDIR)/input-verification.o
	$(CXX) $(CXXFLAGS) $(LDFLAGS) -o $@ $^ $(LDLIBS)

verify-min-index: $(OBJDIR)/verify-min-index.o $(COMMON_OBJS)
	$(CXX) $(CXXFLAGS) $(LDFLAGS) -o $@ $^ $(LDLIBS)

verify-minimized: $(OBJDIR)/verify-minimized.o $(COMMON_OBJS) $(LOOKUP_OBJS)
	$(CXX) $(CXXFLAGS) $(LDFLAGS) -o $@ $^ $(LDLIBS) $(LOOKUP_LDLIBS)

verify-new: $(OBJDIR)/verify-new.o $(COMMON_OBJS)
	$(CXX) $(CXXFLAGS) $(LDFLAGS) -o $@ $^ $(LDLIBS)

verify-r0: $(OBJDIR)/verify-r0.o $(COMMON_OBJS)
	$(CXX) $(CXXFLAGS) $(LDFLAGS) -o $@ $^ $(LDLIBS)

verify-r1: $(OBJDIR)/verify-r1.o $(COMMON_OBJS)
	$(CXX) $(CXXFLAGS) $(LDFLAGS) -o $@ $^ $(LDLIBS)

verify-rN: $(OBJDIR)/verify-rN.o $(COMMON_OBJS)
	$(CXX) $(CXXFLAGS) $(LDFLAGS) -o $@ $^ $(LDLIBS)

test-client: $(OBJDIR)/client/test-client.o $(COMMON_OBJS) $(CLIENT_OBJS)
	$(CXX) $(CXXFLAGS) $(LDFLAGS) -o $@ $^ $(LDLIBS) $(CLIENT_LDLIBS)

# EOF
